[dir.qemu]
attend = "$HOME/.sys/mnt/qemu/attend"
disk = "$HOME/.sys/mnt/qemu/disk"
iso = "$HOME/.sys/mnt/qemu/iso"
nvram = "$HOME/.sys/mnt/qemu/nvram"

[fcos]
meta_url = 'https://builds.coreos.fedoraproject.org/streams/stable.json'

[img.qemu.low]
cores     = 4 
memory    = 8
