version = '0.0.0-3'
kernel = 'kernel'
programs = [
  'example/helloworld',
  'example/bounce',
  'example/wasd',
  'test/exitstatus',
  'test/badstore',
  'test/displayprint',
  'test/framecap',
  'test/keys',
  'test/blocklist',
  'test/romfs',
  'test/tar',
  'test/gz'
]
