version = '0.0.0-7'
kernel = 'kernel'
programs = [
  'example/helloworld',
  'example/bounce',
  'example/wasd',
  'example/logo',
  'test/exitstatus',
  'test/badstore',
  'test/displayprint',
  'test/framecap',
  'test/keys',
  'test/blocklist',
  'test/romfs',
  'test/tar',
  'test/gz',
  'test/checksum',
  'test/hash',
  'test/png',
  'test/sprite',
  'test/purity'
]
