# spleen.nu: generate the kernel's console font from a Spleen BDF.
#
#   nu spleen.nu <spleen-12x24.bdf> <src/font.S>
#
# Takes the printable ASCII glyphs, 32 to 126, from the BDF, each 24
# rows of 16 bits with the 12-pixel glyph in the high bits, and writes
# them as an assembler table the kernel indexes by character. Spleen is
# BSD 2-clause; its license is at doc/thirdparty/spleen/LICENSE.
use std/assert

def main [bdf: path, out: path] {
    let text = (open --raw $bdf | decode)
    let version = ($text | lines | where {|l| $l =~ '^COMMENT  \* Spleen ' } | first | str replace -r '^COMMENT  \* ' '')
    let glyphs = ($text | split row "STARTCHAR " | skip 1 | each {|c|
        let ls = ($c | lines)
        let code = ($ls | where {|l| $l | str starts-with "ENCODING " } | first | str replace "ENCODING " "" | into int)
        let bitmap = ($ls | enumerate | where {|e| $e.item == "BITMAP" } | first | get index)
        let end = ($ls | enumerate | where {|e| $e.item == "ENDCHAR" } | first | get index)
        { code: $code, name: ($ls | first), rows: ($ls | slice ($bitmap + 1)..<$end) }
    } | where {|g| $g.code >= 32 and $g.code <= 126 } | sort-by code)
    assert equal ($glyphs | length) 95 "the printable ASCII glyphs"
    for g in $glyphs { assert equal ($g.rows | length) 24 $"24 rows for ($g.code)" }
    let header = [
        "# font.S: the console font, Spleen 12x24 (spleen-12x24.bdf from"
        $"# ($version), BSD 2-clause, doc/thirdparty/spleen/LICENSE): the printable"
        "# ASCII glyphs 32 to 126 in order, each 24 rows of 16 bits with the"
        "# glyph in the high 12 bits. Generated by kernel/font/spleen.nu; do not"
        "# edit by hand."
        ".section .rodata"
        ".balign 4"
        ".global font_glyphs"
        "font_glyphs:"
    ]
    let body = ($glyphs | each {|g|
        let rows = ($g.rows | each {|r| "0x" + ($r | str lowercase) } | chunks 8 | each {|c| "    .2byte " + ($c | str join ", ") })
        [$"# ($g.code) ($g.name)"] ++ $rows | str join "\n"
    })
    ($header ++ $body | str join "\n") + "\n" | save -f $out
    print $"($out): 95 glyphs from ($version)"
}
